### ISSUE TITLE
HDB-XXX SNOMED Corrections Histologie-Grading

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#100]
https://simplifier.net/medizininformatikinitiative-modulonkologie/mii-cm-onko-grading-sct
**Zeilen 13-21** 
Anpassen wie folgt
Kommentar bei 0 ändern zu "Es gibt kein passendes Konzept unter dem Parent-Konzept "370114008 | Histological grades (qualifier value) |" oder generell in der Hierarchie "362981000 | Qualifier value (qualifier value) |"

Anpassung der SNOMED-Targets für 1-4 wie folgt

1: 1155701009 | G1: Well differentiated histologic grade (qualifier value)   
2: 1155703007 | G2: Moderately differentiated histologic grade   (qualifier value) 
3: 1155704001 | G3: Poorly differentiated histologic grade (qualifier value)  
4: 1155702002 | G4: Undifferentiated histologic grade (qualifier value)

**Comment by Gauxi** [comment]
done

**Comment by ThomasDeBe** [comment]
Passt!
