### ISSUE TITLE
HDB-XXX SNOMED Corrections Therapie Stellung 

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#101]
https://simplifier.net/medizininformatikinitiative-modulonkologie/mii-cm-onko-therapie-stellung-sct

Zeile 24
Change FSN to "Neoadjuvant intent (qualifier value)" ( neuer FSN seit Mai-Version)

**Comment by Gauxi** [comment]
done

**Comment by ThomasDeBe** [comment]
Done!
