### ISSUE TITLE
HDB-367 ICD-O-3 Topographie als Observation.bodySite in Verlaufshistologie

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#103]
https://simplifier.net/guide/mii-ig-modul-onkologie-2024-de/MIIIGModulOnkologie/TechnischeImplementierung/FHIR-Profile/Histologie/Verlaufshistologie-Observation.page.md?version=current

Hier einmal analog zur Diagnose ICD-O-3 als bodySite hinterlegen. 
Bitte Suchparameter und Beispiele überprüfen und ggfs. anpassen

**Comment by Gauxi** [comment]
Die Änderung müssen wir uns nochmal gemeinsam angucken

**Comment by ThomasDeBe** [comment]
passt, habe das Mapping und den IG entsprechend geändert
