### ISSUE TITLE
Fix CapabilityStatement

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#116]
Vorlage (CapabilityStatement vom MolGen):
https://github.com/medizininformatik-initiative/kerndatensatzmodul-GenetischeTests/blob/main/input/fsh/CapabilityStatement.fsh

für jedes Profil: 
- Anpassen Ressourcentyp (z.B. Condition bei Diagnose)
- Anpassen Canonical FHIR URL (z.b. http://hl7.org/fhir/StructureDefinition/Condition)
- Anpassen Canonical Profil URL  
- Hinzufügen aller MS / Search Parameter aus dem  IG
-  Abgleichen, ob Search Parameter nach Änderungen noch aktuell sind (  

Achtung: entgegen der Vorbesprechung muss ein Suchparameter nur 1x hinzugefügt werden (also nicht für z.B. jedes TNM einzeln)
Im MolGen wurden auch alle Obseravation-Profile und Suchparameter am Stück gemacht und nicht einzeln für jedes Profil- 

Außerdem Hinzufügen der Profile für: 
* Verlaufshistologie (Observation)
* Evidenz Erstdiagnose  (Liste)

**Comment by Gauxi** [comment]
done
