### ISSUE TITLE
CodeSystem Kollision

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-onkologie#29]
Betrifft Datenelement '[Aszites im Ultraschall Score'](https://art-decor.org/ad/#/mide-/datasets/dataset/2.16.840.1.113883.3.1937.777.24.1.1/2018-06-05T12:44:12/concept/2.16.840.1.113883.3.1937.777.24.2.2698/2023-01-11T10:55:55) 
bzw. das dort Verwendete ValueSet '[MII Oncology: Organfunktion - Aszites im Ultraschall Score
](https://art-decor.org/ad/#/mide-/terminology/valueset/2.16.840.1.113883.3.1937.777.24.11.116/2023-01-11T11:33:46)' bzw. konkret das hier verwendete CodeSystem '[MII Oncology: Organfunktion - Aszites im Ultraschall Score
](https://art-decor.org/ad/#/mide-/terminology/codesystems/2.16.840.1.113883.3.1937.777.24.5.2/2023-01-25T21:37:37)'

sowie

Datenelement '[Hepatische Enzephalopathie'](https://art-decor.org/ad/#/mide-/datasets/dataset/2.16.840.1.113883.3.1937.777.24.1.1/2018-06-05T12:44:12/concept/2.16.840.1.113883.3.1937.777.24.2.2699/2023-01-11T10:59:09) 
bzw. das dort Verwendete ValueSet '[MII Oncology: Organfunktion - Hepatische Enzephalopathie](https://art-decor.org/ad/#/mide-/terminology/valueset/2.16.840.1.113883.3.1937.777.24.11.117/2023-01-11T12:21:46)' bzw. konkret das hier verwendete CodeSystem '[MII Oncology: Organfunktion - Hepatische Enzephalopathie](https://art-decor.org/ad/#/mide-/terminology/codesystems/2.16.840.1.113883.3.1937.777.24.5.3/2023-01-25T21:44:42)'

Die OIDs dieser CodeSysteme (2.16.840.1.113883.3.1937.777.24.5.2 und 2.16.840.1.113883.3.1937.777.24.5.3) wurde bereits für CodeSystemen des Erw.moduls Consent verwendet, allerdings zu einer Zeit, wo ART-DECOR das noch nicht unterstützt hat. Die Verwendung dieser CodeSysteme erfolgt in den folgenden ValueSets, welche bereits vom NSG verabschiedet wurden (Informationsmodell und Ballotierung):
[MII Consent: Answer ValueSet](https://art-decor.org/ad/#/mide-/terminology/valueset/2.16.840.1.113883.3.1937.777.24.11.30/2021-03-23T23:45:09): OID=2.16.840.1.113883.3.1937.777.24.5.2
[MII Consent: Policy ValueSet](https://art-decor.org/ad/#/mide-/terminology/valueset/2.16.840.1.113883.3.1937.777.24.11.36/2023-01-18T13:08:49): OID=2.16.840.1.113883.3.1937.777.24.5.3

Vorschlag: Die OIDs sollte auf eine freie und nicht verwendete OID geändert werden, z.B. 2.16.840.1.113883.3.1937.777.24.5.5 und 2.16.840.1.113883.3.1937.777.24.5.6

**Comment by cybernop** [comment]
@JoriKern

**Comment by kheitmann** [comment]
Wir vom ART-DECOR Team werden uns der vorgeschlagenen Änderung annehmen, da Änderungen an OIDs nachträglich immer etwas tricky sein können. Das Problem ist morgen früh behoben.

**Comment by kheitmann** [comment]
Die OIDs wurden getauscht auf ..24.5.5 und 24.5.6 und in den Value Sets entsprechend geändert. Die ursprünglichen "älteren" Value Sets sind unangetastet. Der Clash sollte damit hier behoben sein. Siehe auch Issue in ART-DECOR https://art-decor.org/ad/#/mide-/issues/issues/2.16.840.1.113883.3.1937.777.24.6.67

**Comment by SebStaeubert** [comment]
@kheitmann Vielen Dank! 
Passt zwar nicht direkt zu diesem Ticket, ist aber eine Folge davon, siehe [Ticket 68](https://art-decor.org/ad/#/mide-/issues/issues/2.16.840.1.113883.3.1937.777.24.6.68) und [Ticket 69](https://art-decor.org/ad/#/mide-/issues/issues/2.16.840.1.113883.3.1937.777.24.6.69) im ART-DECOR. THX!

**Comment by kheitmann** [comment]
Ist geändert.

**Comment by kheitmann** [comment]
Sebastian,

 

die Tickets habe ich bearbeitet und geschlossen.

 

Mit freundlichen Grüßen

--Kai Heitmann

*--------------------------------------------------------------

| Dr. Kai U. Heitmann, MD, FHL7

|

| Heitmann Consulting and Services (Germany)

| ART-DECOR Open Tools GmbH

| ART-DECOR® Expert Group art-decor.org

| CEO HL7 Deutschland e. V.

| Founder hl7.tv

|

| mobile DE:+49.172.2660814

| Skype: kaiheitmann

| ***@***.***

*--------------------------------------------------------------

 

 

Von: Sebastian Stäubert ***@***.***>
Antworten an: medizininformatik-initiative/kerndatensatzmodul-onkologie ***@***.***>
Datum: Montag, 27. März 2023 um 17:47
An: medizininformatik-initiative/kerndatensatzmodul-onkologie ***@***.***>
Cc: "Kai U. Heitmann" ***@***.***>, Mention ***@***.***>
Betreff: Re: [medizininformatik-initiative/kerndatensatzmodul-onkologie] CodeSystem Kollision (Issue #29)

 

@kheitmann Vielen Dank!
Passt zwar nicht direkt zu diesem Ticket, ist aber eine Folge davon, siehe Ticket 68 und Ticket 69 im ART-DECOR. THX!

**Comment by SebStaeubert** [comment]
@kheitmann vielen Dank!
Da gäbe es jetzt noch ein [Ticket 70](https://art-decor.org/ad/#/mide-/issues/issues/2.16.840.1.113883.3.1937.777.24.6.70) in dem Zusammenhang. 
(Sorry, dass ich dieses Ticket hier dafür missbrauche - ich bin mir nicht sicher, ob dieses Ticket sonst wahrgenommen wird und wenn ja, ob ich darüber informiert werden.)

**Comment by kheitmann** [comment]
Siehe https://art-decor.org/ad/#/mide-/issues/issues/2.16.840.1.113883.3.1937.777.24.6.70 meine Frage

**Comment by ThomasDeBe** [comment]
Das Ticket ist fast ein Jahr alt und bezieht sich auf die Art-Decor-Modellierung, und hat sich erledigt. Case closed!
