### ISSUE TITLE
High-Alert Medication Recherche

### ISSUE THREAD

**Issue by MichaelSponfeldner** [medizininformatik-initiative/kerndatensatzmodul-onkologie#38]

**Comment by ThomasDeBe** [comment]
@MichaelSponfeldner Danke für das Ticket, ich kann mich nicht erinnern dass wir im Rahmen der Onko oder Molekulares-Tumorboard-Meetings darüber gesprochen haben. Ist das Ticket hier richtig? Wenn ja, würde ich mich über den Kontext freuen. Danke :)
