### ISSUE TITLE
Strahlentherapie.outcome coding MS 

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#58]

**Comment by Gauxi** [comment]
Der Wert ist aktuell MS. Das soll dann nicht mehr MS sein?

**Comment by ThomasDeBe** [comment]
@Gauxi 
outcome ist MS; aber das coding und outcome.coding.code und coding.system sollen auch MS.

**Comment by Gauxi** [comment]
done
