### ISSUE TITLE
Fehler in Codes für Verlauf-Observation und Components

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#59]
HDP-Ticket 375
"Für Observation.code.coding sollte ein Binding auf MII_CS_Onko_Verlauf_Gesamtbeurteilung vorgenommen werden. Das Observation.code.coding in der Component-sclice „Lymphknotenverlauf“ ist falsch, richtig ist 399656008 |Status of tumor metastasis to regional lymph nodes (observable entity)|. Das Observation.code.coding in der Component-sclice „Fernmetastasenverlauf“ ist falsch, richtig ist 399608002 |Status of distant metastasis (observable entity)|."

--> Korrekt, TODOs: 

- Observation.valueCodeableConcept vom LymphknotenValueset auf das Gesamtbeurteilungs-ValueSet abändern
-  component[Lymphknoten_Verlauf].code ändern zu 399656008 |Status of tumor metastasis to regional lymph nodes (observable entity)|. 
- component[Fernmetastasen_Verlauf].code ändern zu 399608002 |Status of distant metastasis (observable entity)|. 

außerdem: 
- MS in den relevanten Component-feldern ergänzen
- Observation.code hat noch kein Binding, hier korrekten SNOMED-CT-Concept ergänzen (muss noch definiert werden, ggfs. 396432002 | Status of regression of tumor (observable entity) |

**Comment by Gauxi** [comment]
Korrekturen eingearbeitet.
Aber MS in den relevanten Component-feldern ergänzen -> was wird hier noch konkret als relevant erachtet?
Observation.code hab ich erstmal wie vorgeschlagen auf 396432002 gesetzt

**Comment by ThomasDeBe** [comment]
passt
