### ISSUE TITLE
 Fernmetastasen add display value to Observation.code pattern for improved readibility

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#60]
![image](https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/assets/152993075/0b8a9973-70d5-4b34-8e38-cb6feb6db715)

**Comment by Gauxi** [comment]
done

**Comment by ThomasDeBe** [comment]
Anpassung beim Review: Das hinzufügen zum display sorgt zwar für bessere Übersicht für jemanden , der sich den IG anschaut, schränkt aber ein. So könnten Systeme weder den Fully Specified Name des Konzepts, noch eine deutsche Übersetzung des Konzepts hinterlegen. Das ist an der Stelle kontraproduktiv. 
Geändert, indem die SNOMED- und oBDS- Beschreibungen auf die Code- und bodySite-Felder 

Achtung: Anderes Ticket schlägt vor, Fernmetstasen auf valueCodeableConcept zu verschieben. Beschreibungen bitte mit umziehen

**Comment by ThomasDeBe** [comment]
Passt.
