### ISSUE TITLE
Rename Module To Gruppen on Abweichungen zum oBDS 

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#62]
Auf folgender Seite, und ggfs. anderen Seiten,  soll auf Bitte der Landeskrebsregister / Tobias Hartz die Formulierung "Modul"/"Module" zu "Gruppe"7"Gruppen" geändert werden. Ausnahme: Die organspezifischen Module. 
https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Onkologie/MIIIGModulOnkologie-Abweichungen-zum-oBDS.html

**Comment by Gauxi** [comment]
Es bleibt aber schon weiterhin bei der Nennung "Erweiterungsmodul"?

**Comment by ThomasDeBe** [comment]
Ja, bitte im Git ändern und nicht im Simplifier @Gauxi

**Comment by Gauxi** [comment]
Erledigt. Allerdings klingt es komisch mit den organspezifischen Modulen dazwischen.

**Comment by ThomasDeBe** [comment]
Klingt komisch, ist aber so^^ (Peter Lustig)
Accepted
