### ISSUE TITLE
HDB-489 corrections and spelling mistakes

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#69]
Bitte einmal prüfen, ob die rechtschreibfehler noch drinnen sind oder ggfs. durch einen vorhergehenden Release schon behoben wurden. 
Der letzte Punkt bezog sich auf einen Fehler in der ConceptMapURL, die Seite wird mittlerweile angezeigt. 

![image](https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/assets/152993075/b8fdc1bf-b761-4631-8711-b4da408e82ba)

**Comment by ThomasDeBe** [comment]
@Gauxi Ich sehe im Pull Request keine Änderungen im IG. Wurden die Changes hier bereits durch Dresden gemacht, oder hattest du noch Changes von hier im Simplifier angepasst, so dass ich das im PR nicht sehe?

**Comment by Gauxi** [comment]
Korrekturen sind jetzt direkt im Git IG

**Comment by ThomasDeBe** [comment]
Done
