### ISSUE TITLE
HDB-486 Redaktionelle Kommentare der DGHNO

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#70]
Bitte um Prüfung

![image-20240617-163445](https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/assets/152993075/f3e00568-6a25-429b-84f6-b4706ade3492)
![image-20240617-163529](https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/assets/152993075/63e58528-8e80-44ff-9fa1-7003bb5934be)

**Comment by Gauxi** [comment]
Das Leerzeichen in der Überschrift oBDS -SNOMED-CT Mapping lässt sich nicht entfernen. Alle anderen Punkt sind berichtigt.

**Comment by ThomasDeBe** [comment]
Habe ich korrigiert. Die Seitennamen werden im git im IG innerhalb eines Ordners in dem jeweiligen toc.yaml konfiguriert. Die Anzeigenamen dürfen Whitespaces und Sonderzeichen haben, die Dateinamen nicht

**Comment by ThomasDeBe** [comment]
Kann Korrekturen no

**Comment by ThomasDeBe** [comment]
Kann Korrekturen nicht im Git finden. Korrekturen bitte direkt im Git machen, wir kriegen die anderweitig nicht zurücksynchronisiert und die werden einfach überschrieben. @Gauxi

**Comment by Gauxi** [comment]
Korrekturen wurden ins Git übernommen

**Comment by ThomasDeBe** [comment]
Passt
