### ISSUE TITLE
Systemische Therapie Beispiel

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-onkologie#72]
https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/blob/922a64c2c58e73a8253bb8fcd0ca7a12b27029dc/input/fsh/oBDS/16_SystemischeTherapie/mii-exa-onko-systemische-therapie.fsh#L26

```json
    "medicationCodeableConcept": {
        "coding":  [
            {
                "system": "http://fhir.de/CodeSystem/bfarm/atc",
                "code": "L01AA01",
                "version": "Version 2022",
                "display": "Cyclophosphamid"
            },
            {
                "system": "http://fhir.de/CodeSystem/bfarm/atc",
                "code": "01DB01",
                "version": "Version 2022",
                "display": "Doxorubicin"
            }
        ]
    },
```

Sowas muss als zwei MedicationStatement-Ressourcen umgesetzt werden oder Referenz auf Medication-Ressource in der Wirkstoffe gemischt werden, sonst lassen sich Dosisangaben nicht auf die einzelnen Wirkstoffe beziehen.

**Comment by ThomasDeBe** [comment]
Als zwei einzelne Examples umsetzen, die dann aber den Referenz über partOf zur gleichen Procedure (MII Onko Systemische Therapie) haben

**Comment by ThomasDeBe** [comment]
Ich musste hier noch den Index korrigiren, im zweiten Beispiel hatten alle Einträge noch den Index 1 statt 0
