### ISSUE TITLE
Profil genetische Variante. value[x]

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-onkologie#74]
https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/blob/922a64c2c58e73a8253bb8fcd0ca7a12b27029dc/input/fsh/oBDS/23_GenetischeVariante/mii-pr-onko-genetische-variante.fsh#L22

```
* value[x] ^slicing.discriminator.type = #pattern
* value[x] ^slicing.rules = #open
* value[x] ^slicing.ordered = false
```

Die Slicing Definition kann hier weggelassen werden. 

```
* value[x] only CodeableConcept
```

Sollte ausreichen und SUSHI macht den Rest. `#pattern` ist hier verkehrt. `value[x]`-Slices sind `#type` und `#closed`, wenn man es explizit definieren möchte, dann so:

```
* value[x] ^slicing.discriminator.type = #type
* value[x] ^slicing.discriminator.path = "$this"
* value[x] ^slicing.rules = #closed
```

**Comment by Gauxi** [comment]
Im Code angepasst

**Comment by ThomasDeBe** [comment]
Sushi läuft damit auf jeden Fall nicht durch 
@julsas Vorschläge? Sonst würde ich das wieder rückgängig machen
![image](https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/assets/152993075/58c4899a-3088-40d8-bc56-73d9e146dad3)

**Comment by julsas** [comment]
Komisch, muss irgendwas im Parent nicht stimmen.
Versuch mal:
```
* value[x] ^slicing.discriminator.type = #type
* value[x] ^slicing.discriminator.path = "$this"
* value[x] ^slicing.rules = #closed
```

**Comment by ThomasDeBe** [comment]
Ja, habe deinen Vorschlag nochmal auskommentiert, dann geht es. 
Korrektur angenommen, damit nehme ich es rein. Danke!
