### ISSUE TITLE
HDP-492 Finding site

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-onkologie#75]
https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/blob/922a64c2c58e73a8253bb8fcd0ca7a12b27029dc/input/fsh/oBDS/11_Fernmetastasen/mii-pr-onko-fernmetastasen.fsh#L44

Hier ist finding site -> bodySite, aber Modul Patho macht valueCodeableConcept. vgl. die Biopsy site Bsps. sind anders modelliert.
https://github.com/medizininformatik-initiative/kerndatensatzmodul-PathologieBefund/blob/77ed42a2081df211af3a1069aa0c93abb59e5a8f/input/fsh/patho-findings.fsh#L33

**Comment by ThomasDeBe** [comment]
Hmm guter Punkt, ggfs. kann man das direkt so modellieren, dass es (nach Anpassungen) auch konform zum PathoFinding ist.
Hier ist natürlich zu beachten, dass nicht alle Fernmetastasen pathologisch / histologisch abgeklärt werden, sondern auch nur klinisch / bildgebend - in dem Fall sind sie vsl. nicht Teil eines Pathoberichts. 
Eine Konformität schadet aber nicht.  Change angenommen. Ich backporte das mal als HDB-Ticket

**Comment by ThomasDeBe** [comment]
https://hl7germany.atlassian.net/jira/servicedesk/projects/HDB/queues/custom/43/HDB-492

**Comment by ThomasDeBe** [comment]
@Gauxi Kannst du das einmal bitte auf deinem bisherigen Branch anpassen? Ich habe die Sushi-Pipeline wieder komplett 

Nicht wundern, ich habe im Fernmetastasen-Profil den Display-Value doch als short / definition der Felder verwendet, das ist technisch an der Stelle sauberer

**Comment by ThomasDeBe** [comment]
Bitte hier den IG-Text auf der Profilseite auch direkt anpassen, um klarzumachen, dass es hier um möglichst große Konformität zum MII Patho Finding geht (mit Link)

**Comment by ThomasDeBe** [comment]
Habe ich jetzt selbst gemacht
