### ISSUE TITLE
HDB-484 Tickets

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#80]
based on: https://hl7germany.atlassian.net/jira/servicedesk/projects/HDB/queues/custom/43/HDB-484

Extension Stellung
- correct Extension name "Stellung" to "StellungZurOp" in both Strahlentherapie and Systemische Therapie
- also change within the example files

Todesursache 
- change cardinality of death valueCodeableConcept to 0..1 in cases where exact cause of death is not known to the hospital

Procedures (OP, Strahlentherapie, Systemische Therapie) are not distinguishable (except for profile)
- add additional mandatory slices to the three profiles
- eg this for surgery: 387713003 | Surgical procedure (procedure) |
- look for other suitable ones for chemotherapy and radiation therapy

**Comment by YuanPeng08** [comment]
Hallo @ThomasDeBe 

die Änderungen für 'Extension Stellung' und 'Todesursache' habe ich bereits im Branch vorgenommen.
Bei dem dritten Punkt bin ich unsicher, wie ich die Profile anpassen soll.
Hast du vielleicht eine Idee?

LG Yuan

**Comment by ThomasDeBe** [comment]
@YuanPeng08  perfekt :) 
Ich würde einen zusätzlichen code bei category einfügen, der immer automatisch gesetzt ist. Als Vorlage kannst du den PathoReport nehmen: https://github.com/medizininformatik-initiative/kerndatensatzmodul-PathologieBefund/blob/main/input/fsh/pathology-report.fsh 
Hier hat jeder Pathoreport automatische einen festgelegten LOINC-Code - category sollte dann MS sein und die Kardinalität sollte  auf 1..* hochgesetzt werden.  
So kann category später auch noch von anderen Feldern belegt werden

**Comment by YuanPeng08** [comment]
Bei dem Element Category bin ich noch ein wenig verwirrt.

Alle Profil erbten die MII KDS Basis Procedure Profil. In diesem Profil wird bereits ein ValueSets von Snomed für Category definiert. Welches Snomed Code für Category verwendet wird, ist abhängig von dem OPS Code Kapitelnummer.

Zum Beispiel, wenn ein OPS Code in der Kapitel 1(Diagnostische Massnahmen) ist, dann wird 165197003 (Diagnostic assessment) SnomedCode in Category geschrieben.

Laut die OPS Katalog sind systemische Therapie und Strahlentherapie in der Kapitel 8, daher sollen beide ein SnomedCode 277132007 (Therapeutic procedure) in Category haben.

Meine Verwirrung daher ist, reicht diese Informationen nicht aus? Wenn man mit FHIR Anfragen erstellt, sollte die Anfragen nicht eigentlich code.coding.code basiert? In diesem Fall sind die drei Profilen (nämlich OP, Systemische Therapie und Strahlentherapie) schon 'sauber getrennt'?

LG Yuan

**Comment by ThomasDeBe** [comment]
Hallo, 
danke für den Hinweis, ich habe es mir nochmal genauer angeguckt. 
Tatsächlich gibt es ein Preferred Binding auf die OPS-Kategorien in SNOMED. Das habe ich erst nicht gesehen, weil das Binding nicht auf dem Procedure.category-Level ist (da ist nur ein SNOMED-Example-Binding), sondern auf Procedure.category.coding[sct]-Slice-Level. https://simplifier.net/mii-basismodul-prozedur-2024/mii-vs-prozedur-opskategorien-snomedct

Wie du sagst, haben leider Strahlentherapie und Systemische Therapie die gleiche category. Das sind aber sehr unterschiedliche Therapien, und eine high-level- Unterscheidung ist evtl. später im Feasibility Check wichtig. Daher würde ich die folgenden Codes mit 
- 1287742003 |Radiotherapy (procedure)| für OPS 8-52 Strahlentherapie
- 371572003 |Nuclear medicine procedure (procedure)| für OPS 8-53 (Nuklearmedizinische Therapie)
- 18629005 |Administration of drug or medicament (procedure)| OPS 8-54  (und ggfs. andere)

Du hast aber recht, dass du in dem Fall an dem Profil nichts ändern musst, weil das Binding ja Preferred ist - ich werde das vielleicht einfach als kleine Tabelle auf die Strahlentherapie-Seite packen.

**Comment by ThomasDeBe** [comment]
Hint from Oncology Session- also reduce cardinalities for other data fields
