### ISSUE TITLE
HDB-435 - move ICD-O-3 Morphology from Condition.code to Condition.extension

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#82]
[HDB-435](https://hl7germany.atlassian.net/browse/HDB-435)

**Comment by ThomasDeBe** [comment]
Erstellen einer Extension
histologyMorphologyBehaviorICDO3
Required Binding auf ICDO3
Einbinden als Extension auf Top Level in Onko Diagnose

Vorlage in mCODE
https://hl7.org/fhir/us/mcode/stu3/StructureDefinition-mcode-primary-cancer-condition.html

Extension, die als Vorlage genutzt werden kann (CS  / VS bitte anpassen und auf ICD-O-3 limitieren; id auf MII Naming Convention anpassen)
https://hl7.org/fhir/us/mcode/stu3/ValueSet-mcode-histology-morphology-behavior-vs.html
[histologyMorphologyBehavior](https://hl7.org/fhir/us/mcode/stu3/StructureDefinition-mcode-primary-cancer-condition-definitions.html#diff_Condition.extension:histologyMorphologyBehavior)

**Comment by Gauxi** [comment]
Done

**Comment by ThomasDeBe** [comment]
Korrekt, Informationen auf IG hinzugefügt
