### ISSUE TITLE
HDB-431 Falsches Binding in Bestrahlungs-Extension

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#83]
https://hl7germany.atlassian.net/browse/HDB-431

TODO: 
- in Bestrahlungs-Extension bei **Gesamtdosis** das Binding von valueQuantitiy.unit auf valueQuantity setzen (eine Ebene höher)
- in Bestrahlungs-Extension bei **Einzeldosis** das Binding von valueQuantitiy.unit auf valueQuantity setzen
-  bei beiden : valueQuantity.system = UCUM setzen

**Comment by Gauxi** [comment]
Done. Ich habe keinen Zugriff auf das jira board. Bitte überprüfen.

**Comment by ThomasDeBe** [comment]
Korrekt implementiert
