### ISSUE TITLE
HDB-426 Corrections und Example files

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#84]
TODO:

Problem: Bei TNM-Seiten werden alle Beispiele nicht gerendert
- vorhandene Beispiele korrekt in Seiten einbinden
- für TNM-Profile ohne Beispiele bitte valide Beispiele erstellen

---

Problem: Bei derVerlaufsobservation  gibt es kein Beispiel
- bitte Beispiel anlegen und einbinden
---
Problem: bei Systemische Therapie wird kein Beispiel gerendert
- bitte vorhandenes Beispiel einbinden (falsche id)

Danke :)

**Comment by ThomasDeBe** [comment]
Bitte noch Beispiel für Verlauf und die Kategorien ergänzen (S, L, V, Pn; siehe UICC Code System im gleichen Ordner)

**Comment by ThomasDeBe** [comment]
Beispiele für Symbole schaue ich mir danach an.

**Comment by Gauxi** [comment]
Done

**Comment by ThomasDeBe** [comment]
done und gemerged
