### ISSUE TITLE
HDB-422 Profil Studienteilnahme

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#85]
TODO 
- neues Profil Studienteilnahme : Observation mit SNOMED Code 70709491003 |Enrollment in clinical trial (procedure)| und dem ja, nein, unbekannt als ValueSet

- neues Beispiel dazu anlegen
- neue Seite im IG anlegen

**Comment by Gauxi** [comment]
Done. Hier bitte IG noch um weitere Erklärungstexte erweitern

**Comment by ThomasDeBe** [comment]
Note to self: Bitte IG Seite direkt im git ergänzen

**Comment by ThomasDeBe** [comment]
Mit folgenden Änderungen angenommen
- Text im IG angepasst
- focus in Profilierung hinzugefügt
- interpretation aus Beispiel gelöscht
- Studienteilnahme-Ordner im Simplifier toc.yaml hinzugefügt
