### ISSUE TITLE
HDB-404 Korrektur ConceptMap-Fehler bei Abszess

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#88]
Korrektur des Indexes in Operations-Komplikation

![image](https://github.com/user-attachments/assets/fff4d3ee-c4ad-4f80-b710-51c7f463d515)

**Comment by Gauxi** [comment]
done

**Comment by ThomasDeBe** [comment]
korrekt
