### ISSUE TITLE
HDB-403 naming convention for ConceptMaps

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#89]
Korrektur der Bennenung von ConceptMaps
- ConceptMap-IDs sollen laut mii im `kebab-case`  sein, so wie die Dateinamen. 
- Die IDs der ConceptMaps werden aus dem FSH-Instance-Feld generiert
- Der Anzeigename ist unter name
- In unserer Implementierung ist das häufig vertauscht. 
Bitte bei allen relevanten ConceptMaps korrigieren. Dabei auch bitte die Namen und ids an die fsh-Dateinamen angleichen. 

![image](https://github.com/user-attachments/assets/1c6b26ae-0698-4239-bce4-1fa5203f4aea)

**Comment by Gauxi** [comment]
Ich konnte keinen Fall finden, in dem der name nicht im kebab-case?

**Comment by ThomasDeBe** [comment]
Quasi name und Instance tauschen
 ( bei Instance dann die id ohne Anführunsstriche, und bei Name einen Lesbaren namen ohne Zwischen-den-Wörtern-Bindestriche

**Comment by Gauxi** [comment]
done

**Comment by ThomasDeBe** [comment]
Review erfolgt - habe die IDs nochmal angepasst, so dass Dateinamen, url und Instance jetzt identisch sind. 

Außerdem wurde der Ordner `overlapping-terminologies` vergessen, den passe ich mit an.
