### ISSUE TITLE
Referenz CCP-Bio 

### ISSUE THREAD

**Issue by CeciliaEngels** [medizininformatik-initiative/kerndatensatzmodul-onkologie#91]
Liebe Noemi, würdest Du beim IG noch die Referent zu CCP-Bio aufnehmen? https://dktk.dkfz.de/en/clinical-platform/working-groups-partners/ccp-bio

**Comment by ThomasDeBe** [comment]
@JoriKern Was denkst du hier? Lass das kommende WOche nochmal besprechen.

**Comment by CeciliaEngels** [comment]
Oh, sorry! @ThomasDeBe! Bin im falschen Repo gelandet! CCP-Bio gehört natürlich zu Biobank/Bioproben... #MeaCulpa Please delete the issue here!
