### ISSUE TITLE
HDB-XXX SNOMED Corrections Tod

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#97]
Tod: https://simplifier.net/medizininformatikinitiative-modulonkologie/mii-cm-onko-tod-sct

**Zeile 8** 
Äquivalenzlevel von Unbekannt auf "equivalent" setzen

**Comment by Gauxi** [comment]
done

**Comment by ThomasDeBe** [comment]
passt.
