### ISSUE TITLE
HDB-XXX SNOMED Corrections Genetische Variante

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#98]
https://simplifier.net/guide/mii-ig-modul-onkologie-2024-de/MIIIGModulOnkologie/TechnischeImplementierung/oBDS-SNOMED-CT-Mapping/Genetische-Variante-Auspraegung.page.md?version=current

**Zeile 9**: Hier fehlt beim zweiten Satz das Verb.  im Git ergänzen:  "übermittelt"

**Comment by Gauxi** [comment]
done

**Comment by ThomasDeBe** [comment]
Passt!
