### ISSUE TITLE
HDB-XXX SNOMED Corrections Therapieplanung

### ISSUE THREAD

**Issue by ThomasDeBe** [medizininformatik-initiative/kerndatensatzmodul-onkologie#99]
Kommentar: 
https://simplifier.net/guide/mii-ig-modul-onkologie-2024-de/MIIIGModulOnkologie/TechnischeImplementierung/oBDS-SNOMED-CT-Mapping/Therapieplanung.page.md?version=current

**Zeile 11** 
Ersetzen des oBDS-Labels posttherapeutisch mit  "posttherapeutisch (nach Therapieabschluss, zur Evaluation durchgeführter oder Planung weiterer Therapien / Nachsorge"
(Quelle: https://plattform65c.atlassian.net/wiki/spaces/Dokumentat/pages/75333744/Tumorkonferenz+Therapieplanung) 

Kommentar zu posttherapeutisch: 
"Könnte problematisch sein, dass "303110006 | Postprocedural period (qualifier value) |" das Parent-Konzept von 262061000 | Postoperative period (qualifier value) | ist.
Alternative Ansätze:  Generelle Verwendung von 225292002 | Developing a treatment plan (procedure) | oder720006006 |Cancer care review (procedure)| , aber hier keine Postkoordination möglich"

**Comment by Gauxi** [comment]
done

**Comment by ThomasDeBe** [comment]
done
